export const s = {
  pageHeader: { marginBottom: 24 },
  pageTitle: { fontSize: 22, fontWeight: 700 },
  seccion: { marginBottom: 28 },
  secTitulo: { fontSize: 13, fontWeight: 700, color: '#6B7280', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 12 },
  tarjetasGrid: { display: 'flex', flexWrap: 'wrap', gap: 10 },
  tarjeta: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', width: 110, height: 90, borderRadius: 8, border: '1px solid #E5E7EB', background: '#FFF', cursor: 'pointer', padding: 8, gap: 4, position: 'relative' },
  tarjetaActiva: { borderColor: '#BFDBFE', background: '#F0F7FF' },
  tarjetaDes: { opacity: 0.55, cursor: 'default' },
  tarjetaIcono: { fontSize: 22 },
  tarjetaLabel: { fontSize: 12, fontWeight: 600, color: '#374151', textAlign: 'center', lineHeight: 1.3 },
  badge: { position: 'absolute', top: 4, right: 4, background: '#F3F4F6', color: '#9CA3AF', fontSize: 9, padding: '1px 4px', borderRadius: 4 },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 },
  modalCard: { background: '#FFF', borderRadius: 10, padding: 28, width: 560, boxShadow: '0 8px 32px rgba(0,0,0,0.15)', maxHeight: '85vh', overflow: 'auto' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  modalTitle: { fontSize: 18, fontWeight: 700, margin: 0 },
  btnCerrar: { background: 'none', border: 'none', fontSize: 18, color: '#9CA3AF', cursor: 'pointer', padding: 4 },
  negCard: { background: '#F9FAFB', border: '1px solid #E5E7EB', borderRadius: 8, padding: 16 },
  fieldLabel: { display: 'block', fontSize: 12, fontWeight: 600, color: '#374151', marginBottom: 4 },
  fieldInput: { padding: '8px 10px', border: '1px solid #D1D5DB', borderRadius: 6, fontSize: 13 },
  preview: { padding: '8px 12px', background: '#FFF', border: '1px solid #D1D5DB', borderRadius: 6, fontSize: 14, fontFamily: 'monospace', fontWeight: 700, color: '#1E3A5F', minWidth: 100 },
  btnGuardar: { padding: '8px 18px', background: '#1E3A5F', color: '#FFF', border: 'none', borderRadius: 6, fontSize: 13, fontWeight: 600, cursor: 'pointer' },
  ticketPreview: { background: '#FAFAFA', border: '1px dashed #D1D5DB', borderRadius: 6, padding: '10px 14px', fontFamily: 'monospace', fontSize: 12, color: '#374151', marginTop: 12 },
}
